"""Scene graph model package."""

from .types import (
    BlockPosition,
    ChartSeries,
    ChartSpec,
    ChartStyle,
    ComputedNode,
    ComputedPatternElement,
    ComputedDeck,
    ComputedSlide,
    Counters,
    Deck,
    GridDef,
    LayoutDef,
    Node,
    NodeContent,
    PatternSpec,
    ScatterPoint,
    ScatterSeries,
    ShapeSpec,
    Slide,
    SlotDef,
    TableSpec,
    TextFitting,
    TextBlock,
    TextRun,
    Theme,
    ThemeColors,
    ThemeFonts,
    ThemeSpacing,
)
from agent_slides.model.layout_provider import (
    BuiltinLayoutProvider,
    LayoutProvider,
    resolve_layout_provider,
)
from agent_slides.model.constraints import Constraint
from agent_slides.model.design_rules import (
    BlockSpacingRules,
    DesignRules,
    LayoutHints,
    list_design_rules,
    load_design_rules,
)
from agent_slides.model.layouts import (
    get_layout,
    get_slot_names,
    get_text_fitting,
    list_layouts,
)
from agent_slides.model.template_layouts import TemplateLayoutRegistry

__all__ = [
    "ChartSeries",
    "ChartSpec",
    "ChartStyle",
    "ComputedNode",
    "ComputedPatternElement",
    "ComputedDeck",
    "ComputedSlide",
    "Constraint",
    "Counters",
    "Deck",
    "DesignRules",
    "GridDef",
    "BuiltinLayoutProvider",
    "BlockPosition",
    "BlockSpacingRules",
    "LayoutDef",
    "LayoutHints",
    "LayoutProvider",
    "Node",
    "NodeContent",
    "PatternSpec",
    "ScatterPoint",
    "ScatterSeries",
    "ShapeSpec",
    "Slide",
    "SlotDef",
    "TableSpec",
    "TemplateLayoutRegistry",
    "TextFitting",
    "TextBlock",
    "TextRun",
    "Theme",
    "ThemeColors",
    "ThemeFonts",
    "ThemeSpacing",
    "get_layout",
    "get_slot_names",
    "get_text_fitting",
    "list_design_rules",
    "list_layouts",
    "load_design_rules",
    "resolve_layout_provider",
]
